[package]
name = "agent2045"
version = "0.1.0"
authors = ["Adam Roller <adam.c.roller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
